module.exports = {
  config: {
    fontSize: 15,
    fontFamily:
      'Fira Code, Menlo, "MesloLGS NF", "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    cursorColor: "rgba(248,28,229,0.8)",
    cursorShape: "UNDERLINE",
    foregroundColor: "#fff",
    backgroundColor: "rgba(0,0,0,0.3)",
    borderColor: "#333",
    css: "",
    termCSS: "",
    showHamburgerMenu: "",
    showWindowControls: "false",
    padding: "12px 14px",
    colors: {
      black: "#000000",
      red: "#ff0000",
      green: "#33ff00",
      yellow: "#ffff00",
      blue: "#0066ff",
      magenta: "#cc00ff",
      cyan: "#00ffff",
      white: "#d0d0d0",
      lightBlack: "#808080",
      lightRed: "#ff0000",
      lightGreen: "#33ff00",
      lightYellow: "#ffff00",
      lightBlue: "#0066ff",
      lightMagenta: "#cc00ff",
      lightCyan: "#00ffff",
      lightWhite: "#ffffff",
    },
    bell: "false",
    copyOnSelect: true,
    hyperBorder: {
      borderColors: ["#E18335", "#ffffff"],
    },
  },
  plugins: [
    "hyper-material-theme",
    "hyperborder",
    "hyper-opacity",
    "hyper-tab-icons",
    "hyper-search",
    "hypercwd",
    "hyperminimal",
    "hyper-snazzy",
  ],
  localPlugins: [],
};
