#!/bin/sh

# AUTOSTART
$HOME/.config/polybar/launch.sh &
$HOME/.config/compton/launch.sh &

# Set BG and Cursor
feh --bg-fill $HOME/Pictures/Wallpapers/peakpx.jpg
xsetroot -cursor_name left_ptr &

pgrep -x sxhkd > /dev/null || sxhkd &

# Setup Monitors
xrandr --output HDMI-0 --primary --mode 1920x1080 --rotate normal --output DP-1 --mode 1920x1080 --rotate normal --left-of HDMI-0

# Setup Mouse Sens
xinput --set-prop pointer:'USB Gaming Mouse' 'libinput Accel Speed' -1

bspc monitor DP-1 -d I II III IV V 
bspc monitor HDMI-0 -d I II III IV V

bspc config border_width            0
bspc config window_gap              5

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
