#!/bin/sh

# AUTOSTART
$HOME/.config/polybar/launch.sh &
$HOME/.config/compton/launch.sh &

# Set BG and Cursor
feh --bg-fill $HOME/Pictures/Wallpapers/wallhaven-j5v2lm.jpg
xsetroot -cursor_name left_ptr &

# Fix Screen Timout
xset -dpms s off &

# Setup sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Setup Monitors
bspc monitor LVDS-1 -d I II III IV V

# Configs
bspc config border_width            0
bspc config window_gap              5

bspc config bottom_padding          -5
bspc config left_padding            -5
bspc config right_padding           -5

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true

# Rules
bspc rule -a Gnome-calculator state=floating center=false
