#!/bin/sh

# AUTOSTART
$HOME/.config/polybar/launch.sh &
$HOME/.config/picom/launch.sh &

# Set BG and Cursor
feh --bg-fill $HOME/Pictures/Wallpapers/wallhaven-4xgyml.jpg
xsetroot -cursor_name left_ptr &

# Fix Screen Timout
xset -dpms s off &

# Setup sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Setup Monitors
xrandr --output HDMI-0 --primary --mode 1920x1080 --rotate normal --output DP-5 --mode 1920x1080 --rotate normal --left-of HDMI-0

# Setup Mouse Sens
xinput --set-prop pointer:'USB Gaming Mouse' 'libinput Accel Speed' -1

# Configs
bspc monitor DP-5 -d I II III IV V 
bspc monitor HDMI-0 -d I II III IV V

bspc config border_width            0
bspc config window_gap              5

bspc config bottom_padding          5
bspc config left_padding            5
bspc config right_padding           5

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true

# Rules
bspc rule -a Gnome-calculator state=floating center=false
bspc rule -a themes state=floating center=true
bspc rule -a wlw state=floating center=true desktop=^2
bspc rule -a slide-to-text state=floating center=true desktop=^2
bspc rule -a temp-mailer state=floating center=true desktop=^4
bspc rule -a shockvpn-gui state=floating center=true desktop=^4
bspc rule -a Windscribe2 state=floating center=false
bspc rule -a Org.gnome.Nautilus state=floating center=true
bspc rule -a Imager state=floating center=true
bspc rule -a AppRun.wrapped state=floating center=true
bspc rule -a "Docker Desktop" state=floating center=true
bspc rule -a Xephyr state=floating center=true desktop=^4
bspc rule -a ghidra-Ghidra state=floating center=true
bspc rule -a Virt-manager state=floating center=true

# Wallets
bspc rule -a electrum state=floating center=false
bspc rule -a electrum-ltc state=floating center=false
bspc rule -a monero-core state=floating center=true
bspc rule -a dash-qt state=floating center=true
